# Generated by Django 4.2.30 on 2026-05-24 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Relay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal", models.CharField(max_length=200)),
                ("days_per_runner", models.IntegerField(default=3)),
                ("started_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("consecutive_count", models.IntegerField(default=0)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.team"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RelaySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "바톤 대기 중"),
                            ("running", "수행 중"),
                            ("done", "바톤터치 완료"),
                            ("sos", "SOS 발동"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_rescue", models.BooleanField(default=False)),
                (
                    "relay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="relay.relay"
                    ),
                ),
                (
                    "runner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="certifications/")),
                ("certified_at", models.DateTimeField(auto_now_add=True)),
                ("day_number", models.IntegerField()),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="relay.relayslot",
                    ),
                ),
            ],
        ),
    ]
