# Generated by Django 4.2.30 on 2026-05-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relay", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="cert_type",
            field=models.CharField(
                choices=[("start", "시작 인증"), ("end", "종료 인증")],
                default="start",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
