# Generated by Django 4.2.30 on 2026-06-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relay", "0002_certification_cert_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="relayslot",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
