# Generated by Django 4.2.30 on 2026-06-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relay", "0003_relayslot_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relayslot",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="relayslot",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
