# Generated by Django 4.2.30 on 2026-05-27 04:57

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="invite_code",
            field=models.CharField(
                default=home.models.generate_invite_code, max_length=6, unique=True
            ),
        ),
    ]
